import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Glob('*.c')

# add cubemx drivers
src += Split('''
CubeMX_Config/Boot/Src/stm32h7rsxx_hal_msp.c
port/fal_flash_port.c

''')

path = [cwd]
path += [cwd + '/CubeMX_Config/Boot/Inc',
         cwd + '/port']


CPPDEFINES = ['STM32H7S7xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
