import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Glob('*.c')
src += Glob('port/*.c')

# add cubemx drivers
src += Split('''
CubeMX_Config/Appli/Core/Src/stm32h7rsxx_hal_msp.c
''')

path = [cwd]
path += [cwd + '/port']
path += [cwd + '/CubeMX_Config/Appli/Core/Inc']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
